/**
 * Session Memory Tracker
 *
 * Auto-saves session and scratchpad memories during conversation lifecycle.
 * This ensures the AI maintains context across long conversations without
 * hitting context limits, using memory instead of full message history.
 *
 * Session Memory: Stores conversation summaries, key decisions, and progress.
 * Scratchpad Memory: Stores active working state, tool results, and task progress.
 */

import { type ModelMessage } from "ai";
import { embedQuery, type MemoryTier, saveMemory, searchMemories } from "@/lib/ai/memory";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface ConversationState {
  userId: string;
  chatId: string;
  projectId?: string;
  messageCount: number;
  lastSummaryIndex: number;
  currentTask: string | null;
  keyDecisions: string[];
  toolsExecuted: number;
}

export interface SessionMemoryEntry {
  tier: "session" | "scratchpad";
  content: string;
  label?: string;
}

// ─── Memory Auto-Save Functions ─────────────────────────────────────────────

/**
 * Save a session memory entry (conversation context, decisions, progress).
 */
export async function saveSessionMemory(params: {
  userId: string;
  chatId: string;
  projectId?: string;
  content: string;
  label?: string;
}): Promise<void> {
  try {
    await saveMemory({
      userId: params.userId,
      chatId: params.chatId,
      projectId: params.projectId,
      tier: "session",
      content: params.content,
      label: params.label,
      metadata: { type: "conversation_summary", autoGenerated: true },
    });
  } catch (error) {
    // Non-critical, don't throw
    console.warn("[SessionMemory] Failed to save session memory:", error);
  }
}

/**
 * Save a scratchpad memory entry (active working state, tool results).
 */
export async function saveScratchpadMemory(params: {
  userId: string;
  chatId: string;
  projectId?: string;
  content: string;
  label?: string;
}): Promise<void> {
  try {
    await saveMemory({
      userId: params.userId,
      chatId: params.chatId,
      projectId: params.projectId,
      tier: "scratchpad",
      content: params.content,
      label: params.label,
      metadata: { type: "active_state", autoGenerated: true },
    });
  } catch (error) {
    // Non-critical
    console.warn("[SessionMemory] Failed to save scratchpad:", error);
  }
}

// ─── Conversation Summarization ─────────────────────────────────────────────

/**
 * Summarize a set of messages into a compact session memory entry.
 * Called periodically as conversation grows to preserve context in memory.
 */
export async function summarizeAndSaveSessionContext(params: {
  userId: string;
  chatId: string;
  projectId?: string;
  messages: Array<{ role: string; content: string }>;
  summaryIndex: number;
}): Promise<void> {
  const { userId, chatId, projectId, messages, summaryIndex } = params;

  if (messages.length === 0) return;

  // Build a compact summary of recent messages
  const recentMessages = messages.slice(-10); // Last 10 messages
  const summaryParts: string[] = [];

  for (const msg of recentMessages) {
    const role = msg.role === "user" ? "User" : "AI";
    // Truncate long messages
    const content =
      msg.content.length > 200
        ? msg.content.slice(0, 200) + "..."
        : msg.content;
    summaryParts.push(`${role}: ${content}`);
  }

  const summary = `Conversation summary (messages ${Math.max(1, summaryIndex - 9)}-${summaryIndex}):\n\n${summaryParts.join("\n\n")}`;

  await saveSessionMemory({
    userId,
    chatId,
    projectId,
    content: summary,
    label: `Conversation summary - messages up to ${summaryIndex}`,
  });
}

/**
 * Save key decisions made during conversation.
 */
export async function saveKeyDecision(params: {
  userId: string;
  chatId: string;
  projectId?: string;
  decision: string;
  context?: string;
}): Promise<void> {
  const { userId, chatId, projectId, decision, context } = params;

  const content = context
    ? `Decision: ${decision}\nContext: ${context}`
    : `Decision: ${decision}`;

  await saveSessionMemory({
    userId,
    chatId,
    projectId,
    content,
    label: `Key decision: ${decision.slice(0, 60)}`,
  });
}

/**
 * Save tool execution results to scratchpad for active state tracking.
 */
export async function trackToolExecution(params: {
  userId: string;
  chatId: string;
  projectId?: string;
  toolName: string;
  input: unknown;
  result: unknown;
  success: boolean;
  durationMs?: number;
}): Promise<void> {
  const { userId, chatId, projectId, toolName, input, result, success, durationMs } = params;

  const inputStr = typeof input === "string" ? input : JSON.stringify(input).slice(0, 200);
  const resultStr = typeof result === "string" ? result : JSON.stringify(result).slice(0, 300);

  const content = [
    `Tool: ${toolName}`,
    `Input: ${inputStr}`,
    `Result: ${resultStr}`,
    `Status: ${success ? "success" : "failed"}`,
    durationMs ? `Duration: ${durationMs}ms` : "",
  ]
    .filter(Boolean)
    .join("\n");

  await saveScratchpadMemory({
    userId,
    chatId,
    projectId,
    content,
    label: `Tool: ${toolName} (${success ? "success" : "failed"})`,
  });
}

/**
 * Save current task progress to scratchpad.
 */
export async function trackTaskProgress(params: {
  userId: string;
  chatId: string;
  projectId?: string;
  task: string;
  step: string;
  progress: number; // 0-100
  details?: string;
}): Promise<void> {
  const { userId, chatId, projectId, task, step, progress, details } = params;

  const content = [
    `Task: ${task}`,
    `Current step: ${step}`,
    `Progress: ${progress}%`,
    details ? `Details: ${details}` : "",
  ]
    .filter(Boolean)
    .join("\n");

  await saveScratchpadMemory({
    userId,
    chatId,
    projectId,
    content,
    label: `Task progress: ${task.slice(0, 50)}`,
  });
}

// ─── Context Building ───────────────────────────────────────────────────────

/**
 * Build compact session context from memory for the AI agent.
 * Uses reranker to select only the most relevant memories,
 * allowing long conversations without hitting context limits.
 */
export async function buildSessionContext(params: {
  userId: string;
  chatId: string;
  projectId?: string;
  currentQuery: string;
  maxTokens?: number;
}): Promise<string> {
  const { userId, chatId, projectId, currentQuery, maxTokens = 2000 } = params;

  const contextParts: string[] = [];

  try {
    // 1. Get recent session memories (conversation summaries)
    const sessionEmbedding = await embedQuery(currentQuery);
    const sessionResults = await searchMemories({
      userId,
      chatId,
      tier: "session",
      query: currentQuery,
      embedding: sessionEmbedding ?? undefined,
      maxResults: 5,
      projectId,
    });

    if (sessionResults.length > 0) {
      const sessionContext = sessionResults
        .map((r) => r.entry.content)
        .join("\n\n");
      contextParts.push(`## Conversation Context\n${sessionContext}`);
    }

    // 2. Get current scratchpad state (active working memory)
    const scratchpadResults = await searchMemories({
      userId,
      chatId,
      tier: "scratchpad",
      query: currentQuery,
      embedding: sessionEmbedding ?? undefined,
      maxResults: 5,
      projectId,
    });

    if (scratchpadResults.length > 0) {
      const scratchpadContext = scratchpadResults
        .map((r) => r.entry.content)
        .join("\n\n");
      contextParts.push(`## Active Working State\n${scratchpadContext}`);
    }

    // 3. Get relevant semantic memories (long-term user facts)
    const semanticResults = await searchMemories({
      userId,
      chatId,
      tier: "semantic",
      query: currentQuery,
      embedding: sessionEmbedding ?? undefined,
      maxResults: 3,
      projectId,
    });

    if (semanticResults.length > 0) {
      const semanticContext = semanticResults
        .map((r) => `[${r.entry.label || "User fact"}] ${r.entry.content}`)
        .join("\n");
      contextParts.push(`## User Context\n${semanticContext}`);
    }
  } catch (error) {
    console.warn("[SessionContext] Error building context:", error);
  }

  if (contextParts.length === 0) {
    return "";
  }

  const fullContext = contextParts.join("\n\n");

  // Rough token estimate: ~4 chars per token
  const estimatedTokens = Math.ceil(fullContext.length / 4);

  if (estimatedTokens > maxTokens) {
    // Truncate context to fit within token limit
    const maxChars = maxTokens * 4;
    return fullContext.slice(0, maxChars) + "\n\n[Context truncated to fit token limit]";
  }

  return fullContext;
}

/**
 * Determine if conversation should use session-memory-based context
 * instead of full message history. Returns true when conversation is long
 * enough that memory-based context would be more efficient.
 */
export function shouldUseSessionContext(params: {
  messageCount: number;
  estimatedTokens: number;
  thresholdTokens?: number;
}): boolean {
  const { messageCount, estimatedTokens, thresholdTokens = 50_000 } = params;

  // Use session context when:
  // 1. More than 20 messages (conversation is getting long)
  // 2. Estimated tokens exceed threshold
  return messageCount > 20 || estimatedTokens > thresholdTokens;
}
